name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AI Code Review
        uses: olahsymbo/ai-code-review-action@v2
        with:
          token_github: ${{ secrets.TOKENGITHUB }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}